# Generated by Django 4.1.13 on 2025-03-04 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(max_length=17, unique=True)),
                ('nickname', models.CharField(max_length=50)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('profile_url', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime_total', models.IntegerField(default=0)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('scout_time', models.IntegerField(default=0)),
                ('soldier_time', models.IntegerField(default=0)),
                ('pyro_time', models.IntegerField(default=0)),
                ('demoman_time', models.IntegerField(default=0)),
                ('heavy_time', models.IntegerField(default=0)),
                ('engineer_time', models.IntegerField(default=0)),
                ('medic_time', models.IntegerField(default=0)),
                ('sniper_time', models.IntegerField(default=0)),
                ('spy_time', models.IntegerField(default=0)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='tf2_api.player')),
            ],
        ),
    ]
